# Generated by Django 4.1.7 on 2023-04-12 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_completion_date', models.DateField()),
                ('priority', models.IntegerField(default=-1)),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('scheduled', models.BooleanField(default=False)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_bom', to='bom.bom')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='release_project', to='projects.projects')),
            ],
            options={
                'verbose_name': 'Release',
            },
        ),
        migrations.CreateModel(
            name='ScheduleItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing', models.IntegerField(blank=True, choices=[(1, 'Laser'), (2, 'Weld'), (3, 'Press'), (4, 'Machine'), (5, 'Cut'), (6, 'Paint')], null=True)),
                ('routing_time', models.IntegerField(blank=True, null=True)),
                ('preroute_finish_datetime', models.DateTimeField(blank=True, null=True)),
                ('work_datetime', models.DateTimeField(blank=True, null=True)),
                ('work_finish_datetime', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('preroute_schedule_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_part_reverse', to='schedule.scheduleitems')),
                ('schedule_line_Item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_lineitems', to='bom.lineitempart')),
                ('schedule_part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_parts', to='bom.parts')),
                ('schedule_release', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_releases', to='schedule.release')),
            ],
            options={
                'verbose_name': 'Schedule Items',
            },
        ),
    ]
