# Generated by Django 4.1.7 on 2023-03-26 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_completion_date', models.DateField()),
                ('priority', models.IntegerField(default=-1)),
                ('release_date', models.DateField()),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='bom.bom')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.projects')),
            ],
        ),
    ]
