# Generated by Django 4.1.7 on 2023-04-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitems',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduleitems',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
