# Generated by Django 4.1.7 on 2023-04-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_scheduleitems_is_complete_scheduleitems_is_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitems',
            name='worker_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
