# Generated by Django 4.1.7 on 2023-04-22 21:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_scheduleitems_route_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.IntegerField(blank=True, choices=[(1, 'Laser'), (2, 'Weld'), (3, 'Press'), (4, 'Machine'), (5, 'Cut'), (6, 'Paint')], null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('percent_complete', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('predecessor_routes', models.ManyToManyField(related_name='routes_pred_routes', to='schedule.routetask')),
                ('release', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes_release', to='schedule.release')),
                ('schedule_items', models.ManyToManyField(related_name='routes_schedule_items', to='schedule.scheduleitems')),
            ],
        ),
    ]
