# Generated by Django 4.1.7 on 2023-04-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_release_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
