# Generated by Django 4.1.7 on 2023-04-09 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0010_parts_routing1_time_parts_routing2_time_and_more'),
        ('schedule', '0004_alter_release_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing', models.IntegerField(blank=True, choices=[(1, 'Laser'), (2, 'Weld'), (3, 'Press'), (4, 'Machine'), (5, 'Cut'), (6, 'Paint')], null=True)),
                ('preroute_finish_datetime', models.DateTimeField(blank=True, null=True)),
                ('work_datetime', models.DateTimeField(blank=True, null=True)),
                ('work_finish_datetime', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_parts', to='bom.parts')),
            ],
        ),
    ]
