# Generated by Django 4.1.7 on 2023-04-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_routetask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routetask',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Status Active'), (2, 'Status Suspended'), (3, 'Status Done'), (4, 'Status Undefined')], null=True),
        ),
    ]
