# Generated by Django 4.1.7 on 2023-04-09 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projects_options'),
        ('bom', '0011_alter_bom_line_items_and_more'),
        ('schedule', '0006_alter_release_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleitems',
            name='part',
        ),
        migrations.AddField(
            model_name='scheduleitems',
            name='line_item_schedule_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_parts', to='bom.lineitempart'),
        ),
        migrations.AlterField(
            model_name='release',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_bom', to='bom.bom'),
        ),
        migrations.AlterField(
            model_name='release',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='release_project', to='projects.projects'),
        ),
    ]
