# Generated by Django 4.1.7 on 2023-04-09 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0011_alter_bom_line_items_and_more'),
        ('schedule', '0008_remove_scheduleitems_line_item_schedule_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitems',
            name='schedule_line_Item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_lineitems', to='bom.parts'),
        ),
    ]
