# Generated by Django 4.1.7 on 2023-04-09 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0011_alter_bom_line_items_and_more'),
        ('schedule', '0009_scheduleitems_schedule_line_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitems',
            name='schedule_line_Item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_lineitems', to='bom.lineitempart'),
        ),
    ]
