# Generated by Django 4.1.7 on 2023-04-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_alter_scheduleitems_schedule_line_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
