# Generated by Django 4.1.7 on 2023-04-11 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_release_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitems',
            name='prerout_schedule_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_part_reverse', to='schedule.scheduleitems'),
        ),
    ]
