# Generated by Django 4.1.7 on 2023-04-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_rename_prerout_schedule_item_scheduleitems_preroute_schedule_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitems',
            name='routing_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
