# Generated by Django 4.1.7 on 2023-04-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constantvals',
            name='cut_worker_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='constantvals',
            name='laser_worker_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='constantvals',
            name='machine_worker_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='constantvals',
            name='paint_worker_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='constantvals',
            name='press_worker_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='constantvals',
            name='weld_worker_qty',
            field=models.IntegerField(null=True),
        ),
    ]
