# Generated by Django 4.1.7 on 2023-04-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0002_alter_constantvals_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='constantvals',
            name='cut_max_work',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='constantvals',
            name='laser_max_work',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='constantvals',
            name='machine_max_work',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='constantvals',
            name='paint_max_work',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='constantvals',
            name='press_max_work',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='constantvals',
            name='weld_max_work',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='constantvals',
            name='post_date',
            field=models.DateField(null=True),
        ),
    ]
