# Generated by Django 4.1.7 on 2023-04-22 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_pn', models.CharField(max_length=30, null=True)),
                ('manufacturing_pn', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('routing1', models.IntegerField(blank=True, choices=[(1, 'Laser'), (2, 'Weld'), (3, 'Press'), (4, 'Machine'), (5, 'Cut'), (6, 'Paint')], null=True)),
                ('routing1_time', models.IntegerField(blank=True, null=True)),
                ('routing2', models.IntegerField(blank=True, choices=[(1, 'Laser'), (2, 'Weld'), (3, 'Press'), (4, 'Machine'), (5, 'Cut'), (6, 'Paint')], null=True)),
                ('routing2_time', models.IntegerField(blank=True, null=True)),
                ('routing3', models.IntegerField(blank=True, choices=[(1, 'Laser'), (2, 'Weld'), (3, 'Press'), (4, 'Machine'), (5, 'Cut'), (6, 'Paint')], null=True)),
                ('routing3_time', models.IntegerField(blank=True, null=True)),
                ('routing4', models.IntegerField(blank=True, choices=[(1, 'Laser'), (2, 'Weld'), (3, 'Press'), (4, 'Machine'), (5, 'Cut'), (6, 'Paint')], null=True)),
                ('routing4_time', models.IntegerField(blank=True, null=True)),
                ('vendor1', models.CharField(max_length=30, null=True)),
                ('cost1', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('is_active_vendor1', models.BooleanField(default=False)),
                ('vendor2', models.CharField(max_length=30, null=True)),
                ('cost2', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('is_active_vendor2', models.BooleanField(default=False)),
                ('vendor3', models.CharField(max_length=30, null=True)),
                ('cost3', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('is_active_vendor3', models.BooleanField(default=False)),
                ('is_assembly', models.BooleanField(default=False)),
                ('is_purchased', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Company Part',
            },
        ),
        migrations.CreateModel(
            name='LineItemPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('calc_cost', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('assembly_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineitem_assembly_part', to='bom.lineitempart')),
                ('line_item_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitem_parts', to='bom.parts')),
            ],
            options={
                'verbose_name': 'BOM Line Item',
            },
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_name', models.CharField(max_length=30, null=True)),
                ('calc_cost', models.DecimalField(decimal_places=3, max_digits=9, null=True)),
                ('line_items', models.ManyToManyField(related_name='bom_line_item_parts', to='bom.lineitempart')),
            ],
            options={
                'verbose_name': 'BOM',
            },
        ),
    ]
