# Generated by Django 4.1.7 on 2023-03-26 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_pn', models.CharField(max_length=30)),
                ('manufacturing_pn', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
                ('routing1', models.IntegerField(choices=[(1, 'Laser'), (2, 'Weld'), (3, 'Press'), (4, 'Machine'), (5, 'Cut'), (6, 'Paint')])),
                ('routing2', models.IntegerField(choices=[(1, 'Laser'), (2, 'Weld'), (3, 'Press'), (4, 'Machine'), (5, 'Cut'), (6, 'Paint')])),
                ('routing3', models.IntegerField(choices=[(1, 'Laser'), (2, 'Weld'), (3, 'Press'), (4, 'Machine'), (5, 'Cut'), (6, 'Paint')])),
                ('routing4', models.IntegerField(choices=[(1, 'Laser'), (2, 'Weld'), (3, 'Press'), (4, 'Machine'), (5, 'Cut'), (6, 'Paint')])),
                ('color', models.CharField(max_length=30)),
                ('is_assembly', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LineItemPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('is_complete', models.BooleanField(default=False)),
                ('calc_cost', models.DecimalField(decimal_places=3, max_digits=9, null=True)),
                ('assembly_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assembly_part', to='bom.parts')),
                ('line_item_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='bom.parts')),
            ],
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_cost', models.DecimalField(decimal_places=3, max_digits=9, null=True)),
                ('calc_date', models.DateField()),
                ('line_items', models.ManyToManyField(related_name='line_item_parts', to='bom.lineitempart')),
            ],
        ),
    ]
