# Generated by Django 4.1.7 on 2023-03-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bom',
            options={'verbose_name': 'BOM'},
        ),
        migrations.AlterModelOptions(
            name='lineitempart',
            options={'verbose_name': 'BOM Line Item'},
        ),
        migrations.AlterModelOptions(
            name='parts',
            options={'verbose_name': 'Company Part'},
        ),
        migrations.AddField(
            model_name='parts',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parts',
            name='routing1',
            field=models.IntegerField(choices=[(1, 'Laser'), (2, 'Weld'), (3, 'Press'), (4, 'Machine'), (5, 'Cut'), (6, 'Paint')], null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='routing2',
            field=models.IntegerField(choices=[(1, 'Laser'), (2, 'Weld'), (3, 'Press'), (4, 'Machine'), (5, 'Cut'), (6, 'Paint')], null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='routing3',
            field=models.IntegerField(choices=[(1, 'Laser'), (2, 'Weld'), (3, 'Press'), (4, 'Machine'), (5, 'Cut'), (6, 'Paint')], null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='routing4',
            field=models.IntegerField(choices=[(1, 'Laser'), (2, 'Weld'), (3, 'Press'), (4, 'Machine'), (5, 'Cut'), (6, 'Paint')], null=True),
        ),
    ]
