# Generated by Django 4.1.7 on 2023-03-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0002_alter_bom_options_alter_lineitempart_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitempart',
            name='calc_cost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='routing1',
            field=models.IntegerField(blank=True, choices=[(1, 'Laser'), (2, 'Weld'), (3, 'Press'), (4, 'Machine'), (5, 'Cut'), (6, 'Paint')], null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='routing2',
            field=models.IntegerField(blank=True, choices=[(1, 'Laser'), (2, 'Weld'), (3, 'Press'), (4, 'Machine'), (5, 'Cut'), (6, 'Paint')], null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='routing3',
            field=models.IntegerField(blank=True, choices=[(1, 'Laser'), (2, 'Weld'), (3, 'Press'), (4, 'Machine'), (5, 'Cut'), (6, 'Paint')], null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='routing4',
            field=models.IntegerField(blank=True, choices=[(1, 'Laser'), (2, 'Weld'), (3, 'Press'), (4, 'Machine'), (5, 'Cut'), (6, 'Paint')], null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
    ]
