# Generated by Django 4.0 on 2023-03-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0003_alter_lineitempart_calc_cost_alter_parts_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='bom_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bom',
            name='line_items',
            field=models.ManyToManyField(related_name='line_item_parts', to='bom.LineItemPart'),
        ),
    ]
