# Generated by Django 4.0 on 2023-03-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0004_bom_bom_name_alter_bom_line_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='calc_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='lineitempart',
            name='qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='internal_pn',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='manufacturing_pn',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
