# Generated by Django 4.1.7 on 2023-03-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0005_alter_bom_calc_date_alter_lineitempart_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='cost1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='parts',
            name='cost2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='parts',
            name='cost3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='parts',
            name='vendor1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='parts',
            name='vendor2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='parts',
            name='vendor3',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
