# Generated by Django 4.1.7 on 2023-03-29 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0006_parts_cost1_parts_cost2_parts_cost3_parts_vendor1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bom',
            name='calc_date',
        ),
    ]
