# Generated by Django 4.1.7 on 2023-03-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0007_remove_bom_calc_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='is_active_vendor1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parts',
            name='is_active_vendor2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parts',
            name='is_active_vendor3',
            field=models.BooleanField(default=False),
        ),
    ]
