# Generated by Django 4.1.7 on 2023-04-06 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0008_parts_is_active_vendor1_parts_is_active_vendor2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitempart',
            name='assembly_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assembly_part', to='bom.lineitempart'),
        ),
    ]
