# Generated by Django 4.1.7 on 2023-04-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0009_alter_lineitempart_assembly_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='routing1_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parts',
            name='routing2_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parts',
            name='routing3_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parts',
            name='routing4_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
