# Generated by Django 4.1.7 on 2023-04-09 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0010_parts_routing1_time_parts_routing2_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='line_items',
            field=models.ManyToManyField(related_name='bom_line_item_parts', to='bom.lineitempart'),
        ),
        migrations.AlterField(
            model_name='lineitempart',
            name='assembly_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineitem_assembly_part', to='bom.lineitempart'),
        ),
        migrations.AlterField(
            model_name='lineitempart',
            name='line_item_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitem_parts', to='bom.parts'),
        ),
    ]
